name: Vouchers
main: me.badbones69.vouchers.Main
version: 1.6.3.2
description: >
             Make Custom Vouchers just for your server!
commands:
  Voucher:
    description: Give yourself a Voucher!
    aliases: [vouch]