name: Vouchers
main: me.badbones69.vouchers.Main
version: 1.9
api-version: 1.13
description:  Make Custom Vouchers just for your server!
commands:
  Vouchers:
    description: Give yourself a Voucher!
    aliases: [voucher, vouch]