name: ${project.artifactId}
main: me.badbones69.vouchers.Main
version: ${project.version}${build.number}
api-version: 1.13
description:  Make Custom Vouchers just for your server!
commands:
  Vouchers:
    description: Give yourself a Voucher!
    aliases: [voucher, vouch]