name: Vouchers
main: "${group}.Vouchers"
version: ${version}
api-version: 1.18
description: ${description}

commands:
  Vouchers:
    description: Give yourself a Voucher!
    aliases: [voucher, vouch]