name: Vouchers
main: me.badbones69.vouchers.Vouchers
version: 1.9.1
api-version: 1.18
description: Make Custom Vouchers just for your server!
commands:
  Vouchers:
    description: Give yourself a Voucher!
    aliases: [voucher, vouch]