name: "Vouchers"
main: "${group}.Vouchers"

authors: [BadBones69, RyderBelserion]

version: ${version}
api-version: "1.19"
description: ${description}

softdepend: [PlaceholderAPI]

commands:
  vouchers:
    description: "Manage your vouchers however you want."
    aliases: [voucher]

permissions:
  voucher.admin:
    default: op

  voucher.redeem:
    default: op