name: Vouchers
main: "${group}.Vouchers"
version: ${version}
api-version: 1.13
description: ${description}

commands:
  vouchers:
    description: Give yourself a Voucher!
    aliases: [voucher]
    permission: "voucher.admin"

permissions:
  voucher.admin:
    default: op

  voucher.redeem:
    default: op