[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.2.4" }

[libraries]
itemsadder-api = { group = "com.github.LoneDev6", name = "api-itemsadder", version = "3.6.1" }
oraxen-api = { group = "io.th0rgal", name = "oraxen", version = "1.171.0" }
placeholder-api = { group = "me.clip", name = "placeholderapi", version = "2.11.5" }
head-database-api = { group = "com.arcaniax", name = "HeadDatabase-API", version = "1.3.1" }

vital = { group = "com.ryderbelserion.vital", name = "paper", version = "1.0-snapshot" }

triumph-cmds = { group = "dev.triumphteam", name = "triumph-cmd-bukkit", version = "2.0.0-ALPHA-10" }
triumph-gui = { group = "dev.triumphteam", name = "triumph-gui", version = "3.1.7" }

vault = { group = "com.github.MilkBowl", name = "VaultAPI", version = "1.7.1" }
metrics = { group = "org.bstats", name = "bstats-bukkit", version = "3.0.2" }
config-me = { group = "ch.jalu", name = "configme", version = "1.4.1" }
nbt-api = { group = "de.tr7zw", name = "item-nbt-api", version = "2.12.4" }

worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version = "7.1.0-SNAPSHOT" }

[bundles]
triumph = ["triumph-cmds", "triumph-gui"]