[versions]
# Minecraft
paper = "1.20.6-R0.1-SNAPSHOT"
minecraft = "1.20.6"

# Plugins
itemsadder = "3.6.3-beta-14"
headdatabaseapi = "1.3.1"
placeholderapi = "2.11.6"
oraxen = "1.171.0"

# Core
annotations = "24.1.0"
crazycrates = "0.6"
gson = "2.10.1"
vital = "1.4"

decentholograms = "2.8.8"
fancyholograms = "2.0.6"

triumph-cmd = "2.0.0-ALPHA-10"
tirumph-gui = "3.1.7"

worldguard = "7.0.10"

paperweight="1.7.1"
shadowJar = "8.1.7"
runPaper = "2.3.0"
minotaur = "2.+"
hangar = "0.1.2"

nbtapi = "2.12.4"

[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
shadowJar = { id = "io.github.goooler.shadow", version.ref = "shadowJar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
# Servers
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Plugins
decent-holograms = { module = "com.github.decentsoftware-eu:decentholograms", version.ref = "decentholograms" }
fancy-holograms = { module = "de.oliver:FancyHolograms", version.ref = "fancyholograms" }

headdatabaseapi = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabaseapi" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }

worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }

nbtapi = { module = "de.tr7zw:item-nbt-api", version.ref = "nbtapi" }

itemsadder = { module = "com.github.LoneDev6:api-itemsadder", version.ref = "itemsadder" }
oraxen = { module = "io.th0rgal:oraxen", version.ref = "oraxen" }

# Libraries
triumph-cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version.ref = "triumph-cmd" }
triumph-gui = { module = "dev.triumphteam:triumph-gui", version.ref = "tirumph-gui" }

crazycrates = { module = "us.crazycrew.crazycrates:api", version.ref = "crazycrates" }

annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

vital-paper = { module = "com.ryderbelserion.vital:paper", version.ref = "vital" }
vital-core = { module = "com.ryderbelserion.vital:core", version.ref = "vital" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[bundles]
holograms = ["decent-holograms", "fancy-holograms"]

triumph = ["triumph-cmds", "triumph-gui"]

items = ["itemsadder", "oraxen"]