[versions]

# Paper Team
paper = "1.19.2-R0.1-SNAPSHOT"

# Triumph Team
triumph-cmd-bukkit = "2.0.0-SNAPSHOT"

# Bukkit
bukkit-bstats = "3.0.0"

# Placeholders
placeholder-api = "2.11.2"

# Misc Libraries
nbt-api = "2.10.0"
vault-api = "1.7"

[libraries]

# Paper Team
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Spigot Team
spigot = { module = "org.spigotmc:spigot-api", version.ref = "paper" }

# Bukkit
bukkit-bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bukkit-bstats" }

# Placeholders
placeholder-api = { module = "me.clip:placeholderapi", version.ref = "placeholder-api" }

# NBT API Libraries
nbt-api = { module = "de.tr7zw:nbt-data-api", version.ref = "nbt-api" }

# Misc Libraries
vault-api = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault-api" }