[versions]

# Minecraft
paper = "1.19.4-R0.1-SNAPSHOT"

# Adventure
kyori = "4.13.0"

ktor = "2.2.4"
kotlin = "1.8.20"

[libraries]

# Minecraft
papermc = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
paperlib = { module = "io.papermc:paperlib", version = "1.0.8-SNAPSHOT" }
paperweight = { module = "io.papermc.paperweight:paperweight-userdev", version = "1.5.4" }

# Adventure
kyori = { module = "net.kyori:adventure-api", version.ref = "kyori" }
kyori-mm = { module = "net.kyori:adventure-text-minimessage", version.ref = "kyori" }

# Triumph Team
triumph_cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version = "2.0.0-SNAPSHOT" }

# Misc
nbt_api = { module = "de.tr7zw:item-nbt-api", version = "2.11.2" }
bstats_bukkit = { module = "org.bstats:bstats-bukkit", version = "3.0.0" }

# CMI
cmi_api = { module = "com.Zrips.CMI:CMI-API", version = "9.3.1.5" }
cmi_lib = { module = "net.zrips.CMILib:cmi-lib-api", version = "1.2.5.3" }

# Placeholders
placeholder_api = { module = "me.clip:placeholderapi", version = "2.11.3" }

# Kotlin
ktor-core = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-content = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }

kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin"}
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }

minotaur = { module = "com.modrinth.minotaur:Minotaur", version = "2.7.5" }

shadow = { module = "com.github.johnrengelman:shadow", version = "8.1.1" }

turtle = { module = "com.lordcodes.turtle:turtle", version = "0.8.0" }