[versions]
modrinth = "2.8.2"
hangar = "0.0.5"

[plugins]
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
modrinth = { id = "com.modrinth.minotaur", version.ref = "modrinth" }