[versions]

# Minecraft
paper = "1.19.3-R0.1-SNAPSHOT"

[libraries]

# Minecraft
papermc = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Triumph Team
triumph_cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version = "2.0.0-SNAPSHOT" }

# Misc
nbt_api = { module = "de.tr7zw:item-nbt-api", version = "2.11.1" }
bstats_bukkit = { module = "org.bstats:bstats-bukkit", version = "3.0.0" }

# Placeholders
placeholder_api = { module = "me.clip:placeholderapi", version = "2.11.2" }