[versions]

# Minecraft
paper = "1.19.4-R0.1-SNAPSHOT"

# Adventure
kyori = "4.13.0"

[libraries]

# Minecraft
papermc = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
paperlib = { module = "io.papermc:paperlib", version = "1.0.8-SNAPSHOT" }

# Adventure
kyori = { module = "net.kyori:adventure-api", version.ref = "kyori" }
kyori-mm = { module = "net.kyori:adventure-text-minimessage", version.ref = "kyori" }

# Triumph Team
triumph_cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version = "2.0.0-SNAPSHOT" }

# Misc
nbt_api = { module = "de.tr7zw:item-nbt-api", version = "2.11.1" }
bstats_bukkit = { module = "org.bstats:bstats-bukkit", version = "3.0.0" }

# Placeholders
placeholder_api = { module = "me.clip:placeholderapi", version = "2.11.2" }