name: Snapshot Build
on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: false
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@main
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle Properties Import.
        shell: bash
        run: cat gradle.properties >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Shadow Jar
        run: ./gradlew shadowJar --stacktrace

      - name: Repo Publish
        run: ./gradlew publish --stacktrace
        env:
          REPOSITORY_USERNAME: ${{ secrets.CRAZYCREW_USERNAME }}
          REPOSITORY_PASSWORD: ${{ secrets.CRAZYCREW_PASSWORD }}