name: '${name}'
main: '${group}.${name}'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'

softdepend: [HeadDatabase, PlaceholderAPI, Oraxen, ItemsAdder]

folia-supported: true